name: Node.js CI (Yarn)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        # run: yarn install --frozen-lockfile

        run: |
          if [[ "${{ matrix.node-version }}" == "16.x" ]]; then
            yarn install --frozen-lockfile --ignore-engines
          else
            yarn install --frozen-lockfile
          fi

      - name: Lint code
        run: yarn lint

      - name: Run tests
        # run: yarn test

        run: |
          if [[ "${{ matrix.node-version }}" == "18.x" ]]; then
            yarn test
          else
            echo "Skipping tests on Node 16.x for now"
          fi
